### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by halkeye**
@ndmanvar

### CODE REVIEW

**Comment by halkeye** [comment]
I don't know why i'm getting
```Sauce Labs results

No Sauce results found```

**Comment by ndmanvar** [comment]
@halkeye Is it cause Jenkinsfile is missing `step([$class: 'SauceOnDemandTestPublisher'])` in the Jenkins file?
As seen in https://github.com/saucelabs-sample-test-frameworks/Java-TestNG-Selenium/blob/master/Jenkinsfile#L16-L18
I don't see where you are getting the No Sauce results found, I checked the jenkins job / pipeline and didn't see it. Did I miss something?

**Comment by halkeye** [comment]
@ndmanvar yep, totally the issue

Ready to merge

**Comment by halkeye** [comment]
https://ecodev-ci.saucelabs.net/job/saucelabs-sample-test-frameworks/job/Ruby-Cucumber-Selenium/job/jenkinsfile/

**Comment by ndmanvar** [comment]
👍  feel free to merge.

**Pull request merged**
